allowBuilds:
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@fallow-cli/darwin-arm64@3.24.1'
  - '@fallow-cli/darwin-x64@3.24.1'
  - '@fallow-cli/linux-arm64-gnu@3.24.1'
  - '@fallow-cli/linux-arm64-musl@3.24.1'
  - '@fallow-cli/linux-x64-gnu@3.24.1'
  - '@fallow-cli/linux-x64-musl@3.24.1'
  - '@fallow-cli/win32-arm64-msvc@3.24.1'
  - '@fallow-cli/win32-x64-msvc@3.24.1'
  - fallow-type-aware@3.24.1
  - fallow@3.24.1
